/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040201
#define SWIGCSHARP
#define SWIG_DIRECTORS

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NULLPTR nullptr
#else
# define SWIG_NULLPTR NULL
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_NLJsonParserDLL(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_NLJsonParserDLL(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_NLJsonParserDLL(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) do { if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } } while (0)


/* Callback for returning strings to C# without leaking memory */
typedef void * (SWIGSTDCALL* SWIG_CSharpWStringHelperCallback)(const wchar_t *, int length);
static SWIG_CSharpWStringHelperCallback SWIG_csharp_wstring_with_length_callback = NULL;


#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterWStringCallback_NLJsonParserDLL(SWIG_CSharpWStringHelperCallback callback_utf16, SWIG_CSharpWStringHelperCallback callback_utf32) {
  SWIG_csharp_wstring_with_length_callback = sizeof(wchar_t) == 2 ? callback_utf16 : callback_utf32;
}


/* Callback for returning strings to C# without leaking memory */
typedef void (SWIGSTDCALL* SWIG_CSharpWStringExceptionHelperCallback)(const wchar_t *, int length);
static SWIG_CSharpWStringExceptionHelperCallback SWIG_csharp_ApplicationException_callback = NULL;


#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterWStringExceptionCallback_NLJsonParserDLL(SWIG_CSharpWStringExceptionHelperCallback callback_utf16, SWIG_CSharpWStringExceptionHelperCallback callback_utf32) {
  SWIG_csharp_ApplicationException_callback = sizeof(wchar_t) == 2 ? callback_utf16 : callback_utf32;
}

/* -----------------------------------------------------------------------------
 * director_common.swg
 *
 * This file contains support for director classes which is common between
 * languages.
 * ----------------------------------------------------------------------------- */

/*
  Use -DSWIG_DIRECTOR_STATIC if you prefer to avoid the use of the
  'Swig' namespace. This could be useful for multi-modules projects.
*/
#ifdef SWIG_DIRECTOR_STATIC
/* Force anonymous (static) namespace */
#define Swig
#endif
/* -----------------------------------------------------------------------------
 * director.swg
 *
 * This file contains support for director classes so that C# proxy
 * methods can be called from C++.
 * ----------------------------------------------------------------------------- */

#if defined(DEBUG_DIRECTOR_OWNED)
#include <iostream>
#endif
#include <string>
#include <exception>

namespace Swig {
  /* Director base class - not currently used in C# directors */
  class Director {
  };

  /* Base class for director exceptions */
  class DirectorException : public std::exception {
  protected:
    std::string swig_msg;

  public:
    DirectorException(const char *msg) : swig_msg(msg) {
    }

    DirectorException(const std::string &msg) : swig_msg(msg) {
    }

    virtual ~DirectorException() throw() {
    }

    const char *what() const throw() {
      return swig_msg.c_str();
    }
  };

  /* Pure virtual method exception */
  class DirectorPureVirtualException : public DirectorException {
  public:
    DirectorPureVirtualException(const char *msg) : DirectorException(std::string("Attempt to invoke pure virtual method ") + msg) {
    }

    static void raise(const char *msg) {
      throw DirectorPureVirtualException(msg);
    }
  };
}


#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif


#include "nljson.h"


#include <string>


#include <wchar.h>
#include <limits.h>
#ifndef WCHAR_MIN
#  define WCHAR_MIN 0
#endif
#ifndef WCHAR_MAX
#  define WCHAR_MAX 65535
#endif


static void * SWIG_csharp_wstring_callback(const wchar_t *s) {
  return SWIG_csharp_wstring_with_length_callback(s, (int)wcslen(s));
}


#include <string>


#include <map>
#include <algorithm>
#include <stdexcept>


#include <typeinfo>
#include <stdexcept>


#include <vector>
#include <algorithm>
#include <stdexcept>


/* For converting from .NET UTF16 (2 byte unicode) strings. wchar_t is 2 bytes on Windows, 4 bytes on Linux. */
static std::wstring Swig_csharp_UTF16ToWString(const unsigned short *str) {
  if (sizeof(wchar_t) == 2) {
    return std::wstring((wchar_t *)str);
  } else {
    const unsigned short *pBegin(str);
    const unsigned short *ptr(pBegin);

    while (*ptr != 0)
      ++ptr;

    std::wstring result;
    result.reserve(ptr - pBegin);
    while(pBegin != ptr)
      result.push_back(*pBegin++);

    return result;
  }
}

SWIGINTERN std::map< std::wstring,std::shared_ptr< NLJsonAST > >::mapped_type const &std_map_Sl_std_wstring_Sc_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__getitem(std::map< std::wstring,std::shared_ptr< NLJsonAST > > *self,std::map< std::wstring,std::shared_ptr< NLJsonAST > >::key_type const &key){
        std::map< std::wstring, std::shared_ptr< NLJsonAST >, std::less< std::wstring > >::iterator iter = self->find(key);
        if (iter != self->end())
          return iter->second;
        else
          throw std::out_of_range("key not found");
      }
SWIGINTERN void std_map_Sl_std_wstring_Sc_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__setitem(std::map< std::wstring,std::shared_ptr< NLJsonAST > > *self,std::map< std::wstring,std::shared_ptr< NLJsonAST > >::key_type const &key,std::map< std::wstring,std::shared_ptr< NLJsonAST > >::mapped_type const &x){
#ifdef __cpp_lib_map_try_emplace
        (*self).insert_or_assign(key, x);
#else
        (*self)[key] = x;
#endif
      }
SWIGINTERN bool std_map_Sl_std_wstring_Sc_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__ContainsKey(std::map< std::wstring,std::shared_ptr< NLJsonAST > > *self,std::map< std::wstring,std::shared_ptr< NLJsonAST > >::key_type const &key){
        std::map< std::wstring, std::shared_ptr< NLJsonAST >, std::less< std::wstring > >::iterator iter = self->find(key);
        return iter != self->end();
      }
SWIGINTERN void std_map_Sl_std_wstring_Sc_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__Add(std::map< std::wstring,std::shared_ptr< NLJsonAST > > *self,std::map< std::wstring,std::shared_ptr< NLJsonAST > >::key_type const &key,std::map< std::wstring,std::shared_ptr< NLJsonAST > >::mapped_type const &value){
        std::map< std::wstring, std::shared_ptr< NLJsonAST >, std::less< std::wstring > >::iterator iter = self->find(key);
        if (iter != self->end())
          throw std::out_of_range("key already exists");
        self->insert(std::pair< std::wstring, std::shared_ptr< NLJsonAST > >(key, value));
      }
SWIGINTERN bool std_map_Sl_std_wstring_Sc_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__Remove(std::map< std::wstring,std::shared_ptr< NLJsonAST > > *self,std::map< std::wstring,std::shared_ptr< NLJsonAST > >::key_type const &key){
        std::map< std::wstring, std::shared_ptr< NLJsonAST >, std::less< std::wstring > >::iterator iter = self->find(key);
        if (iter != self->end()) {
          self->erase(iter);
          return true;
        }
        return false;
      }
SWIGINTERN std::map< std::wstring,std::shared_ptr< NLJsonAST >,std::less< std::wstring > >::iterator *std_map_Sl_std_wstring_Sc_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__create_iterator_begin(std::map< std::wstring,std::shared_ptr< NLJsonAST > > *self){
        return new std::map< std::wstring, std::shared_ptr< NLJsonAST >, std::less< std::wstring > >::iterator(self->begin());
      }
SWIGINTERN std::map< std::wstring,std::shared_ptr< NLJsonAST > >::key_type const &std_map_Sl_std_wstring_Sc_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__get_next_key(std::map< std::wstring,std::shared_ptr< NLJsonAST > > *self,std::map< std::wstring,std::shared_ptr< NLJsonAST >,std::less< std::wstring > >::iterator *swigiterator){
        (void)self;
        std::map< std::wstring, std::shared_ptr< NLJsonAST >, std::less< std::wstring > >::iterator iter = *swigiterator;
        (*swigiterator)++;
        return (*iter).first;
      }
SWIGINTERN void std_map_Sl_std_wstring_Sc_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__destroy_iterator(std::map< std::wstring,std::shared_ptr< NLJsonAST > > *self,std::map< std::wstring,std::shared_ptr< NLJsonAST >,std::less< std::wstring > >::iterator *swigiterator){
        (void)self;
        delete swigiterator;
      }
SWIGINTERN std::vector< std::shared_ptr< NLJsonAST > > *new_std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg___SWIG_2(int capacity){
        std::vector< std::shared_ptr< NLJsonAST > >* pv = 0;
        if (capacity >= 0) {
          pv = new std::vector< std::shared_ptr< NLJsonAST > >();
          pv->reserve(capacity);
       } else {
          throw std::out_of_range("capacity");
       }
       return pv;
      }
SWIGINTERN std::shared_ptr< NLJsonAST > std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__getitemcopy(std::vector< std::shared_ptr< NLJsonAST > > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN std::vector< std::shared_ptr< NLJsonAST > >::value_type const &std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__getitem(std::vector< std::shared_ptr< NLJsonAST > > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__setitem(std::vector< std::shared_ptr< NLJsonAST > > *self,int index,std::shared_ptr< NLJsonAST > const &val){
        if (index>=0 && index<(int)self->size())
          (*self)[index] = val;
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__AddRange(std::vector< std::shared_ptr< NLJsonAST > > *self,std::vector< std::shared_ptr< NLJsonAST > > const &values){
        self->insert(self->end(), values.begin(), values.end());
      }
SWIGINTERN std::vector< std::shared_ptr< NLJsonAST > > *std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__GetRange(std::vector< std::shared_ptr< NLJsonAST > > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        return new std::vector< std::shared_ptr< NLJsonAST > >(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__Insert(std::vector< std::shared_ptr< NLJsonAST > > *self,int index,std::shared_ptr< NLJsonAST > const &x){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, x);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__InsertRange(std::vector< std::shared_ptr< NLJsonAST > > *self,int index,std::vector< std::shared_ptr< NLJsonAST > > const &values){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, values.begin(), values.end());
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__RemoveAt(std::vector< std::shared_ptr< NLJsonAST > > *self,int index){
        if (index>=0 && index<(int)self->size())
          self->erase(self->begin() + index);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__RemoveRange(std::vector< std::shared_ptr< NLJsonAST > > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        self->erase(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN std::vector< std::shared_ptr< NLJsonAST > > *std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__Repeat(std::shared_ptr< NLJsonAST > const &value,int count){
        if (count < 0)
          throw std::out_of_range("count");
        return new std::vector< std::shared_ptr< NLJsonAST > >(count, value);
      }
SWIGINTERN void std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__Reverse__SWIG_0(std::vector< std::shared_ptr< NLJsonAST > > *self){
        std::reverse(self->begin(), self->end());
      }
SWIGINTERN void std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__Reverse__SWIG_1(std::vector< std::shared_ptr< NLJsonAST > > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        std::reverse(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__SetRange(std::vector< std::shared_ptr< NLJsonAST > > *self,int index,std::vector< std::shared_ptr< NLJsonAST > > const &values){
        if (index < 0)
          throw std::out_of_range("index");
        if (index+values.size() > self->size())
          throw std::out_of_range("index");
        std::copy(values.begin(), values.end(), self->begin()+index);
      }

struct SWIG_null_deleter {
  void operator() (void const *) const {
  }
};
#define SWIG_NO_NULL_DELETER_0 , SWIG_null_deleter()
#define SWIG_NO_NULL_DELETER_1
#define SWIG_NO_NULL_DELETER_SWIG_POINTER_NEW
#define SWIG_NO_NULL_DELETER_SWIG_POINTER_OWN



/* ---------------------------------------------------
 * C++ director class methods
 * --------------------------------------------------- */

#include "NLJsonParser_wrap.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void * SWIGSTDCALL CSharp_new_NLJsonASTDictionary__SWIG_0() {
  void * jresult ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > > *result = 0 ;
  
  result = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *)new std::map< std::wstring,std::shared_ptr< NLJsonAST > >();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_NLJsonASTDictionary__SWIG_1(void * jarg1) {
  void * jresult ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > > *arg1 = 0 ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > > *result = 0 ;
  
  arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::map< std::wstring,std::shared_ptr< NLJsonAST > > const & is null", 0);
    return 0;
  } 
  result = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *)new std::map< std::wstring,std::shared_ptr< NLJsonAST > >((std::map< std::wstring,std::shared_ptr< NLJsonAST > > const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_NLJsonASTDictionary_size(void * jarg1) {
  unsigned int jresult ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > > *arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *) 0 ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > >::size_type result;
  
  arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *)jarg1; 
  result = ((std::map< std::wstring,std::shared_ptr< NLJsonAST > > const *)arg1)->size();
  jresult = (unsigned int)result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_NLJsonASTDictionary_empty(void * jarg1) {
  unsigned int jresult ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > > *arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *) 0 ;
  bool result;
  
  arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *)jarg1; 
  result = (bool)((std::map< std::wstring,std::shared_ptr< NLJsonAST > > const *)arg1)->empty();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonASTDictionary_Clear(void * jarg1) {
  std::map< std::wstring,std::shared_ptr< NLJsonAST > > *arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *) 0 ;
  
  arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *)jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void * SWIGSTDCALL CSharp_NLJsonASTDictionary_getitem(void * jarg1, unsigned short * jarg2) {
  void * jresult ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > > *arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *) 0 ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > >::key_type *arg2 = 0 ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > >::mapped_type *result = 0 ;
  
  arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null wstring", 0);
    return 0;
  }
  std::wstring arg2_str(Swig_csharp_UTF16ToWString(jarg2));
  arg2 = &arg2_str; 
  try {
    result = (std::map< std::wstring,std::shared_ptr< NLJsonAST > >::mapped_type *) &std_map_Sl_std_wstring_Sc_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__getitem(arg1,(std::wstring const &)*arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = *result ? new std::map< std::wstring,std::shared_ptr< NLJsonAST > >::mapped_type(*result) : 0; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonASTDictionary_setitem(void * jarg1, unsigned short * jarg2, void * jarg3) {
  std::map< std::wstring,std::shared_ptr< NLJsonAST > > *arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *) 0 ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > >::key_type *arg2 = 0 ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > >::mapped_type *arg3 = 0 ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > >::mapped_type tempnull3 ;
  
  arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null wstring", 0);
    return ;
  }
  std::wstring arg2_str(Swig_csharp_UTF16ToWString(jarg2));
  arg2 = &arg2_str; 
  arg3 = jarg3 ? (std::map< std::wstring,std::shared_ptr< NLJsonAST > >::mapped_type *)jarg3 : &tempnull3; 
  std_map_Sl_std_wstring_Sc_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__setitem(arg1,(std::wstring const &)*arg2,(std::shared_ptr< NLJsonAST > const &)*arg3);
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_NLJsonASTDictionary_ContainsKey(void * jarg1, unsigned short * jarg2) {
  unsigned int jresult ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > > *arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *) 0 ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > >::key_type *arg2 = 0 ;
  bool result;
  
  arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null wstring", 0);
    return 0;
  }
  std::wstring arg2_str(Swig_csharp_UTF16ToWString(jarg2));
  arg2 = &arg2_str; 
  result = (bool)std_map_Sl_std_wstring_Sc_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__ContainsKey(arg1,(std::wstring const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonASTDictionary_Add(void * jarg1, unsigned short * jarg2, void * jarg3) {
  std::map< std::wstring,std::shared_ptr< NLJsonAST > > *arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *) 0 ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > >::key_type *arg2 = 0 ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > >::mapped_type *arg3 = 0 ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > >::mapped_type tempnull3 ;
  
  arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null wstring", 0);
    return ;
  }
  std::wstring arg2_str(Swig_csharp_UTF16ToWString(jarg2));
  arg2 = &arg2_str; 
  arg3 = jarg3 ? (std::map< std::wstring,std::shared_ptr< NLJsonAST > >::mapped_type *)jarg3 : &tempnull3; 
  try {
    std_map_Sl_std_wstring_Sc_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__Add(arg1,(std::wstring const &)*arg2,(std::shared_ptr< NLJsonAST > const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_NLJsonASTDictionary_Remove(void * jarg1, unsigned short * jarg2) {
  unsigned int jresult ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > > *arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *) 0 ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > >::key_type *arg2 = 0 ;
  bool result;
  
  arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null wstring", 0);
    return 0;
  }
  std::wstring arg2_str(Swig_csharp_UTF16ToWString(jarg2));
  arg2 = &arg2_str; 
  result = (bool)std_map_Sl_std_wstring_Sc_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__Remove(arg1,(std::wstring const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_NLJsonASTDictionary_create_iterator_begin(void * jarg1) {
  void * jresult ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > > *arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *) 0 ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST >,std::less< std::wstring > >::iterator *result = 0 ;
  
  arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *)jarg1; 
  result = (std::map< std::wstring,std::shared_ptr< NLJsonAST >,std::less< std::wstring > >::iterator *)std_map_Sl_std_wstring_Sc_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__create_iterator_begin(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_NLJsonASTDictionary_get_next_key(void * jarg1, void * jarg2) {
  void * jresult ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > > *arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *) 0 ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST >,std::less< std::wstring > >::iterator *arg2 = (std::map< std::wstring,std::shared_ptr< NLJsonAST >,std::less< std::wstring > >::iterator *) 0 ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST > >::key_type *result = 0 ;
  
  arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *)jarg1; 
  arg2 = (std::map< std::wstring,std::shared_ptr< NLJsonAST >,std::less< std::wstring > >::iterator *)jarg2; 
  result = (std::map< std::wstring,std::shared_ptr< NLJsonAST > >::key_type *) &std_map_Sl_std_wstring_Sc_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__get_next_key(arg1,arg2);
  jresult = SWIG_csharp_wstring_with_length_callback(result->data(), (int)result->size()); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonASTDictionary_destroy_iterator(void * jarg1, void * jarg2) {
  std::map< std::wstring,std::shared_ptr< NLJsonAST > > *arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *) 0 ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST >,std::less< std::wstring > >::iterator *arg2 = (std::map< std::wstring,std::shared_ptr< NLJsonAST >,std::less< std::wstring > >::iterator *) 0 ;
  
  arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *)jarg1; 
  arg2 = (std::map< std::wstring,std::shared_ptr< NLJsonAST >,std::less< std::wstring > >::iterator *)jarg2; 
  std_map_Sl_std_wstring_Sc_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__destroy_iterator(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_NLJsonASTDictionary(void * jarg1) {
  std::map< std::wstring,std::shared_ptr< NLJsonAST > > *arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *) 0 ;
  
  arg1 = (std::map< std::wstring,std::shared_ptr< NLJsonAST > > *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_NLJsonASTList__SWIG_0() {
  void * jresult ;
  std::vector< std::shared_ptr< NLJsonAST > > *result = 0 ;
  
  result = (std::vector< std::shared_ptr< NLJsonAST > > *)new std::vector< std::shared_ptr< NLJsonAST > >();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_NLJsonASTList__SWIG_1(void * jarg1) {
  void * jresult ;
  std::vector< std::shared_ptr< NLJsonAST > > *arg1 = 0 ;
  std::vector< std::shared_ptr< NLJsonAST > > *result = 0 ;
  
  arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< std::shared_ptr< NLJsonAST > > const & is null", 0);
    return 0;
  } 
  result = (std::vector< std::shared_ptr< NLJsonAST > > *)new std::vector< std::shared_ptr< NLJsonAST > >((std::vector< std::shared_ptr< NLJsonAST > > const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonASTList_Clear(void * jarg1) {
  std::vector< std::shared_ptr< NLJsonAST > > *arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *) 0 ;
  
  arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonASTList_Add(void * jarg1, void * jarg2) {
  std::vector< std::shared_ptr< NLJsonAST > > *arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *) 0 ;
  std::shared_ptr< NLJsonAST > *arg2 = 0 ;
  std::shared_ptr< NLJsonAST > tempnull2 ;
  
  arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg1; 
  arg2 = jarg2 ? (std::shared_ptr< NLJsonAST > *)jarg2 : &tempnull2; 
  (arg1)->push_back((std::shared_ptr< NLJsonAST > const &)*arg2);
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_NLJsonASTList_size(void * jarg1) {
  unsigned int jresult ;
  std::vector< std::shared_ptr< NLJsonAST > > *arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *) 0 ;
  std::vector< std::shared_ptr< NLJsonAST > >::size_type result;
  
  arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg1; 
  result = ((std::vector< std::shared_ptr< NLJsonAST > > const *)arg1)->size();
  jresult = (unsigned int)result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_NLJsonASTList_empty(void * jarg1) {
  unsigned int jresult ;
  std::vector< std::shared_ptr< NLJsonAST > > *arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *) 0 ;
  bool result;
  
  arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg1; 
  result = (bool)((std::vector< std::shared_ptr< NLJsonAST > > const *)arg1)->empty();
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_NLJsonASTList_capacity(void * jarg1) {
  unsigned int jresult ;
  std::vector< std::shared_ptr< NLJsonAST > > *arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *) 0 ;
  std::vector< std::shared_ptr< NLJsonAST > >::size_type result;
  
  arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg1; 
  result = ((std::vector< std::shared_ptr< NLJsonAST > > const *)arg1)->capacity();
  jresult = (unsigned int)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonASTList_reserve(void * jarg1, unsigned int jarg2) {
  std::vector< std::shared_ptr< NLJsonAST > > *arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *) 0 ;
  std::vector< std::shared_ptr< NLJsonAST > >::size_type arg2 ;
  
  arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg1; 
  arg2 = (std::vector< std::shared_ptr< NLJsonAST > >::size_type)jarg2; 
  (arg1)->reserve(arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_NLJsonASTList__SWIG_2(int jarg1) {
  void * jresult ;
  int arg1 ;
  std::vector< std::shared_ptr< NLJsonAST > > *result = 0 ;
  
  arg1 = (int)jarg1; 
  try {
    result = (std::vector< std::shared_ptr< NLJsonAST > > *)new_std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg___SWIG_2(arg1);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_NLJsonASTList_getitemcopy(void * jarg1, int jarg2) {
  void * jresult ;
  std::vector< std::shared_ptr< NLJsonAST > > *arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *) 0 ;
  int arg2 ;
  std::shared_ptr< NLJsonAST > result;
  
  arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__getitemcopy(arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = result ? new std::shared_ptr< NLJsonAST >(result) : 0; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_NLJsonASTList_getitem(void * jarg1, int jarg2) {
  void * jresult ;
  std::vector< std::shared_ptr< NLJsonAST > > *arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *) 0 ;
  int arg2 ;
  std::vector< std::shared_ptr< NLJsonAST > >::value_type *result = 0 ;
  
  arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< std::shared_ptr< NLJsonAST > >::value_type *) &std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__getitem(arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = *result ? new std::vector< std::shared_ptr< NLJsonAST > >::value_type(*result) : 0; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonASTList_setitem(void * jarg1, int jarg2, void * jarg3) {
  std::vector< std::shared_ptr< NLJsonAST > > *arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *) 0 ;
  int arg2 ;
  std::shared_ptr< NLJsonAST > *arg3 = 0 ;
  std::shared_ptr< NLJsonAST > tempnull3 ;
  
  arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = jarg3 ? (std::shared_ptr< NLJsonAST > *)jarg3 : &tempnull3; 
  try {
    std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__setitem(arg1,arg2,(std::shared_ptr< NLJsonAST > const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonASTList_AddRange(void * jarg1, void * jarg2) {
  std::vector< std::shared_ptr< NLJsonAST > > *arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *) 0 ;
  std::vector< std::shared_ptr< NLJsonAST > > *arg2 = 0 ;
  
  arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg1; 
  arg2 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< std::shared_ptr< NLJsonAST > > const & is null", 0);
    return ;
  } 
  std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__AddRange(arg1,(std::vector< std::shared_ptr< NLJsonAST > > const &)*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_NLJsonASTList_GetRange(void * jarg1, int jarg2, int jarg3) {
  void * jresult ;
  std::vector< std::shared_ptr< NLJsonAST > > *arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *) 0 ;
  int arg2 ;
  int arg3 ;
  std::vector< std::shared_ptr< NLJsonAST > > *result = 0 ;
  
  arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    result = (std::vector< std::shared_ptr< NLJsonAST > > *)std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__GetRange(arg1,arg2,arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  } catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonASTList_Insert(void * jarg1, int jarg2, void * jarg3) {
  std::vector< std::shared_ptr< NLJsonAST > > *arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *) 0 ;
  int arg2 ;
  std::shared_ptr< NLJsonAST > *arg3 = 0 ;
  std::shared_ptr< NLJsonAST > tempnull3 ;
  
  arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = jarg3 ? (std::shared_ptr< NLJsonAST > *)jarg3 : &tempnull3; 
  try {
    std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__Insert(arg1,arg2,(std::shared_ptr< NLJsonAST > const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonASTList_InsertRange(void * jarg1, int jarg2, void * jarg3) {
  std::vector< std::shared_ptr< NLJsonAST > > *arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *) 0 ;
  int arg2 ;
  std::vector< std::shared_ptr< NLJsonAST > > *arg3 = 0 ;
  
  arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< std::shared_ptr< NLJsonAST > > const & is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__InsertRange(arg1,arg2,(std::vector< std::shared_ptr< NLJsonAST > > const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonASTList_RemoveAt(void * jarg1, int jarg2) {
  std::vector< std::shared_ptr< NLJsonAST > > *arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *) 0 ;
  int arg2 ;
  
  arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__RemoveAt(arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonASTList_RemoveRange(void * jarg1, int jarg2, int jarg3) {
  std::vector< std::shared_ptr< NLJsonAST > > *arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__RemoveRange(arg1,arg2,arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  } catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_NLJsonASTList_Repeat(void * jarg1, int jarg2) {
  void * jresult ;
  std::shared_ptr< NLJsonAST > *arg1 = 0 ;
  int arg2 ;
  std::shared_ptr< NLJsonAST > tempnull1 ;
  std::vector< std::shared_ptr< NLJsonAST > > *result = 0 ;
  
  arg1 = jarg1 ? (std::shared_ptr< NLJsonAST > *)jarg1 : &tempnull1; 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< std::shared_ptr< NLJsonAST > > *)std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__Repeat((std::shared_ptr< NLJsonAST > const &)*arg1,arg2);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonASTList_Reverse__SWIG_0(void * jarg1) {
  std::vector< std::shared_ptr< NLJsonAST > > *arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *) 0 ;
  
  arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg1; 
  std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__Reverse__SWIG_0(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonASTList_Reverse__SWIG_1(void * jarg1, int jarg2, int jarg3) {
  std::vector< std::shared_ptr< NLJsonAST > > *arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__Reverse__SWIG_1(arg1,arg2,arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  } catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonASTList_SetRange(void * jarg1, int jarg2, void * jarg3) {
  std::vector< std::shared_ptr< NLJsonAST > > *arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *) 0 ;
  int arg2 ;
  std::vector< std::shared_ptr< NLJsonAST > > *arg3 = 0 ;
  
  arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< std::shared_ptr< NLJsonAST > > const & is null", 0);
    return ;
  } 
  try {
    std_vector_Sl_std_shared_ptr_Sl_NLJsonAST_Sg__Sg__SetRange(arg1,arg2,(std::vector< std::shared_ptr< NLJsonAST > > const &)*arg3);
  } catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_NLJsonASTList(void * jarg1) {
  std::vector< std::shared_ptr< NLJsonAST > > *arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *) 0 ;
  
  arg1 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonAST_name_set(void * jarg1, unsigned short * jarg2) {
  NLJsonAST *arg1 = (NLJsonAST *) 0 ;
  std::wstring *arg2 = 0 ;
  std::shared_ptr< NLJsonAST > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  NLJsonAST > *)jarg1;
  arg1 = (NLJsonAST *)(smartarg1 ? smartarg1->get() : 0); 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null wstring", 0);
    return ;
  }
  std::wstring arg2_str(Swig_csharp_UTF16ToWString(jarg2));
  arg2 = &arg2_str; 
  if (arg1) (arg1)->name = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_NLJsonAST_name_get(void * jarg1) {
  void * jresult ;
  NLJsonAST *arg1 = (NLJsonAST *) 0 ;
  std::shared_ptr< NLJsonAST > *smartarg1 = 0 ;
  std::wstring *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  NLJsonAST > *)jarg1;
  arg1 = (NLJsonAST *)(smartarg1 ? smartarg1->get() : 0); 
  result = (std::wstring *) & ((arg1)->name);
  jresult = SWIG_csharp_wstring_with_length_callback(result->data(), (int)result->size()); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonAST_type_set(void * jarg1, int jarg2) {
  NLJsonAST *arg1 = (NLJsonAST *) 0 ;
  NLJsonType arg2 ;
  std::shared_ptr< NLJsonAST > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  NLJsonAST > *)jarg1;
  arg1 = (NLJsonAST *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (NLJsonType)jarg2; 
  if (arg1) (arg1)->type = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_NLJsonAST_type_get(void * jarg1) {
  int jresult ;
  NLJsonAST *arg1 = (NLJsonAST *) 0 ;
  std::shared_ptr< NLJsonAST > *smartarg1 = 0 ;
  NLJsonType result;
  
  
  smartarg1 = (std::shared_ptr<  NLJsonAST > *)jarg1;
  arg1 = (NLJsonAST *)(smartarg1 ? smartarg1->get() : 0); 
  result = (NLJsonType) ((arg1)->type);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonAST_token_set(void * jarg1, unsigned short * jarg2) {
  NLJsonAST *arg1 = (NLJsonAST *) 0 ;
  std::wstring *arg2 = 0 ;
  std::shared_ptr< NLJsonAST > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  NLJsonAST > *)jarg1;
  arg1 = (NLJsonAST *)(smartarg1 ? smartarg1->get() : 0); 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null wstring", 0);
    return ;
  }
  std::wstring arg2_str(Swig_csharp_UTF16ToWString(jarg2));
  arg2 = &arg2_str; 
  if (arg1) (arg1)->token = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_NLJsonAST_token_get(void * jarg1) {
  void * jresult ;
  NLJsonAST *arg1 = (NLJsonAST *) 0 ;
  std::shared_ptr< NLJsonAST > *smartarg1 = 0 ;
  std::wstring *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  NLJsonAST > *)jarg1;
  arg1 = (NLJsonAST *)(smartarg1 ? smartarg1->get() : 0); 
  result = (std::wstring *) & ((arg1)->token);
  jresult = SWIG_csharp_wstring_with_length_callback(result->data(), (int)result->size()); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonAST_list_set(void * jarg1, void * jarg2) {
  NLJsonAST *arg1 = (NLJsonAST *) 0 ;
  std::vector< std::shared_ptr< NLJsonAST > > *arg2 = (std::vector< std::shared_ptr< NLJsonAST > > *) 0 ;
  std::shared_ptr< NLJsonAST > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  NLJsonAST > *)jarg1;
  arg1 = (NLJsonAST *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (std::vector< std::shared_ptr< NLJsonAST > > *)jarg2; 
  if (arg1) (arg1)->list = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_NLJsonAST_list_get(void * jarg1) {
  void * jresult ;
  NLJsonAST *arg1 = (NLJsonAST *) 0 ;
  std::shared_ptr< NLJsonAST > *smartarg1 = 0 ;
  std::vector< std::shared_ptr< NLJsonAST > > *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  NLJsonAST > *)jarg1;
  arg1 = (NLJsonAST *)(smartarg1 ? smartarg1->get() : 0); 
  result = (std::vector< std::shared_ptr< NLJsonAST > > *)& ((arg1)->list);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonAST_dict_set(void * jarg1, void * jarg2) {
  NLJsonAST *arg1 = (NLJsonAST *) 0 ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST >,std::less< std::wstring > > *arg2 = (std::map< std::wstring,std::shared_ptr< NLJsonAST >,std::less< std::wstring > > *) 0 ;
  std::shared_ptr< NLJsonAST > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  NLJsonAST > *)jarg1;
  arg1 = (NLJsonAST *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (std::map< std::wstring,std::shared_ptr< NLJsonAST >,std::less< std::wstring > > *)jarg2; 
  if (arg1) (arg1)->dict = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_NLJsonAST_dict_get(void * jarg1) {
  void * jresult ;
  NLJsonAST *arg1 = (NLJsonAST *) 0 ;
  std::shared_ptr< NLJsonAST > *smartarg1 = 0 ;
  std::map< std::wstring,std::shared_ptr< NLJsonAST >,std::less< std::wstring > > *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  NLJsonAST > *)jarg1;
  arg1 = (NLJsonAST *)(smartarg1 ? smartarg1->get() : 0); 
  result = (std::map< std::wstring,std::shared_ptr< NLJsonAST >,std::less< std::wstring > > *)& ((arg1)->dict);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_NLJsonAST() {
  void * jresult ;
  NLJsonAST *result = 0 ;
  
  result = (NLJsonAST *)new NLJsonAST();
  
  jresult = result ? new std::shared_ptr<  NLJsonAST >(result SWIG_NO_NULL_DELETER_1) : 0;
  
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_NLJsonAST(void * jarg1) {
  NLJsonAST *arg1 = (NLJsonAST *) 0 ;
  std::shared_ptr< NLJsonAST > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  NLJsonAST > *)jarg1;
  arg1 = (NLJsonAST *)(smartarg1 ? smartarg1->get() : 0); 
  (void)arg1; delete smartarg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonResult_error_set(void * jarg1, unsigned int jarg2) {
  NLJsonResult *arg1 = (NLJsonResult *) 0 ;
  bool arg2 ;
  std::shared_ptr< NLJsonResult > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  NLJsonResult > *)jarg1;
  arg1 = (NLJsonResult *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->error = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_NLJsonResult_error_get(void * jarg1) {
  unsigned int jresult ;
  NLJsonResult *arg1 = (NLJsonResult *) 0 ;
  std::shared_ptr< NLJsonResult > *smartarg1 = 0 ;
  bool result;
  
  
  smartarg1 = (std::shared_ptr<  NLJsonResult > *)jarg1;
  arg1 = (NLJsonResult *)(smartarg1 ? smartarg1->get() : 0); 
  result = (bool) ((arg1)->error);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonResult_error_msg_set(void * jarg1, unsigned short * jarg2) {
  NLJsonResult *arg1 = (NLJsonResult *) 0 ;
  std::wstring *arg2 = 0 ;
  std::shared_ptr< NLJsonResult > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  NLJsonResult > *)jarg1;
  arg1 = (NLJsonResult *)(smartarg1 ? smartarg1->get() : 0); 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null wstring", 0);
    return ;
  }
  std::wstring arg2_str(Swig_csharp_UTF16ToWString(jarg2));
  arg2 = &arg2_str; 
  if (arg1) (arg1)->error_msg = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_NLJsonResult_error_msg_get(void * jarg1) {
  void * jresult ;
  NLJsonResult *arg1 = (NLJsonResult *) 0 ;
  std::shared_ptr< NLJsonResult > *smartarg1 = 0 ;
  std::wstring *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  NLJsonResult > *)jarg1;
  arg1 = (NLJsonResult *)(smartarg1 ? smartarg1->get() : 0); 
  result = (std::wstring *) & ((arg1)->error_msg);
  jresult = SWIG_csharp_wstring_with_length_callback(result->data(), (int)result->size()); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_NLJsonResult_ast_set(void * jarg1, void * jarg2) {
  NLJsonResult *arg1 = (NLJsonResult *) 0 ;
  std::shared_ptr< NLJsonAST > *arg2 = 0 ;
  std::shared_ptr< NLJsonResult > *smartarg1 = 0 ;
  std::shared_ptr< NLJsonAST > tempnull2 ;
  
  
  smartarg1 = (std::shared_ptr<  NLJsonResult > *)jarg1;
  arg1 = (NLJsonResult *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = jarg2 ? (std::shared_ptr< NLJsonAST > *)jarg2 : &tempnull2; 
  if (arg1) (arg1)->ast = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_NLJsonResult_ast_get(void * jarg1) {
  void * jresult ;
  NLJsonResult *arg1 = (NLJsonResult *) 0 ;
  std::shared_ptr< NLJsonResult > *smartarg1 = 0 ;
  std::shared_ptr< NLJsonAST > *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  NLJsonResult > *)jarg1;
  arg1 = (NLJsonResult *)(smartarg1 ? smartarg1->get() : 0); 
  result = (std::shared_ptr< NLJsonAST > *) & ((arg1)->ast);
  jresult = *result ? new std::shared_ptr< NLJsonAST >(*result) : 0; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_NLJsonResult() {
  void * jresult ;
  NLJsonResult *result = 0 ;
  
  result = (NLJsonResult *)new NLJsonResult();
  
  jresult = result ? new std::shared_ptr<  NLJsonResult >(result SWIG_NO_NULL_DELETER_1) : 0;
  
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_NLJsonResult(void * jarg1) {
  NLJsonResult *arg1 = (NLJsonResult *) 0 ;
  std::shared_ptr< NLJsonResult > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  NLJsonResult > *)jarg1;
  arg1 = (NLJsonResult *)(smartarg1 ? smartarg1->get() : 0); 
  (void)arg1; delete smartarg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_NLJsonParser() {
  void * jresult ;
  NLJsonParser *result = 0 ;
  
  result = (NLJsonParser *)new NLJsonParser();
  
  jresult = result ? new std::shared_ptr<  NLJsonParser >(result SWIG_NO_NULL_DELETER_1) : 0;
  
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_NLJsonParser_Parse(void * jarg1, unsigned short * jarg2) {
  void * jresult ;
  NLJsonParser *arg1 = (NLJsonParser *) 0 ;
  std::wstring *arg2 = 0 ;
  std::shared_ptr< NLJsonParser > *smartarg1 = 0 ;
  std::shared_ptr< NLJsonResult > result;
  
  
  smartarg1 = (std::shared_ptr<  NLJsonParser > *)jarg1;
  arg1 = (NLJsonParser *)(smartarg1 ? smartarg1->get() : 0); 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null wstring", 0);
    return 0;
  }
  std::wstring arg2_str(Swig_csharp_UTF16ToWString(jarg2));
  arg2 = &arg2_str; 
  result = (arg1)->Parse((std::wstring const &)*arg2);
  jresult = result ? new std::shared_ptr< NLJsonResult >(result) : 0; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_NLJsonParser(void * jarg1) {
  NLJsonParser *arg1 = (NLJsonParser *) 0 ;
  std::shared_ptr< NLJsonParser > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  NLJsonParser > *)jarg1;
  arg1 = (NLJsonParser *)(smartarg1 ? smartarg1->get() : 0); 
  (void)arg1; delete smartarg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_CreateParser() {
  void * jresult ;
  std::shared_ptr< NLJsonParser > result;
  
  result = CreateParser();
  jresult = result ? new std::shared_ptr< NLJsonParser >(result) : 0; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

