//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class NLJsonParserDLL {
  public static NLJsonParser CreateParser() {
    global::System.IntPtr cPtr = NLJsonParserDLLPINVOKE.CreateParser();
    NLJsonParser ret = (cPtr == global::System.IntPtr.Zero) ? null : new NLJsonParser(cPtr, true);
    return ret;
  }

}
