//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class NLJsonASTList : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<NLJsonAST>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NLJsonASTList(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NLJsonASTList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(NLJsonASTList obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~NLJsonASTList() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NLJsonParserDLLPINVOKE.delete_NLJsonASTList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public NLJsonASTList(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (NLJsonAST element in c) {
      this.Add(element);
    }
  }

  public NLJsonASTList(global::System.Collections.Generic.IEnumerable<NLJsonAST> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (NLJsonAST element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public NLJsonAST this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(NLJsonAST[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(NLJsonAST[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, NLJsonAST[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public NLJsonAST[] ToArray() {
    NLJsonAST[] array = new NLJsonAST[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<NLJsonAST> global::System.Collections.Generic.IEnumerable<NLJsonAST>.GetEnumerator() {
    return new NLJsonASTListEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new NLJsonASTListEnumerator(this);
  }

  public NLJsonASTListEnumerator GetEnumerator() {
    return new NLJsonASTListEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class NLJsonASTListEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<NLJsonAST>
  {
    private NLJsonASTList collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public NLJsonASTListEnumerator(NLJsonASTList collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public NLJsonAST Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (NLJsonAST)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public NLJsonASTList() : this(NLJsonParserDLLPINVOKE.new_NLJsonASTList__SWIG_0(), true) {
  }

  public NLJsonASTList(NLJsonASTList other) : this(NLJsonParserDLLPINVOKE.new_NLJsonASTList__SWIG_1(NLJsonASTList.getCPtr(other)), true) {
    if (NLJsonParserDLLPINVOKE.SWIGPendingException.Pending) throw NLJsonParserDLLPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    NLJsonParserDLLPINVOKE.NLJsonASTList_Clear(swigCPtr);
  }

  public void Add(NLJsonAST x) {
    NLJsonParserDLLPINVOKE.NLJsonASTList_Add(swigCPtr, NLJsonAST.getCPtr(x));
    if (NLJsonParserDLLPINVOKE.SWIGPendingException.Pending) throw NLJsonParserDLLPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = NLJsonParserDLLPINVOKE.NLJsonASTList_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = NLJsonParserDLLPINVOKE.NLJsonASTList_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = NLJsonParserDLLPINVOKE.NLJsonASTList_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    NLJsonParserDLLPINVOKE.NLJsonASTList_reserve(swigCPtr, n);
  }

  public NLJsonASTList(int capacity) : this(NLJsonParserDLLPINVOKE.new_NLJsonASTList__SWIG_2(capacity), true) {
    if (NLJsonParserDLLPINVOKE.SWIGPendingException.Pending) throw NLJsonParserDLLPINVOKE.SWIGPendingException.Retrieve();
  }

  private NLJsonAST getitemcopy(int index) {
    global::System.IntPtr cPtr = NLJsonParserDLLPINVOKE.NLJsonASTList_getitemcopy(swigCPtr, index);
    NLJsonAST ret = (cPtr == global::System.IntPtr.Zero) ? null : new NLJsonAST(cPtr, true);
    if (NLJsonParserDLLPINVOKE.SWIGPendingException.Pending) throw NLJsonParserDLLPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private NLJsonAST getitem(int index) {
    global::System.IntPtr cPtr = NLJsonParserDLLPINVOKE.NLJsonASTList_getitem(swigCPtr, index);
    NLJsonAST ret = (cPtr == global::System.IntPtr.Zero) ? null : new NLJsonAST(cPtr, true);
    if (NLJsonParserDLLPINVOKE.SWIGPendingException.Pending) throw NLJsonParserDLLPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, NLJsonAST val) {
    NLJsonParserDLLPINVOKE.NLJsonASTList_setitem(swigCPtr, index, NLJsonAST.getCPtr(val));
    if (NLJsonParserDLLPINVOKE.SWIGPendingException.Pending) throw NLJsonParserDLLPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(NLJsonASTList values) {
    NLJsonParserDLLPINVOKE.NLJsonASTList_AddRange(swigCPtr, NLJsonASTList.getCPtr(values));
    if (NLJsonParserDLLPINVOKE.SWIGPendingException.Pending) throw NLJsonParserDLLPINVOKE.SWIGPendingException.Retrieve();
  }

  public NLJsonASTList GetRange(int index, int count) {
    global::System.IntPtr cPtr = NLJsonParserDLLPINVOKE.NLJsonASTList_GetRange(swigCPtr, index, count);
    NLJsonASTList ret = (cPtr == global::System.IntPtr.Zero) ? null : new NLJsonASTList(cPtr, true);
    if (NLJsonParserDLLPINVOKE.SWIGPendingException.Pending) throw NLJsonParserDLLPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, NLJsonAST x) {
    NLJsonParserDLLPINVOKE.NLJsonASTList_Insert(swigCPtr, index, NLJsonAST.getCPtr(x));
    if (NLJsonParserDLLPINVOKE.SWIGPendingException.Pending) throw NLJsonParserDLLPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, NLJsonASTList values) {
    NLJsonParserDLLPINVOKE.NLJsonASTList_InsertRange(swigCPtr, index, NLJsonASTList.getCPtr(values));
    if (NLJsonParserDLLPINVOKE.SWIGPendingException.Pending) throw NLJsonParserDLLPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    NLJsonParserDLLPINVOKE.NLJsonASTList_RemoveAt(swigCPtr, index);
    if (NLJsonParserDLLPINVOKE.SWIGPendingException.Pending) throw NLJsonParserDLLPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    NLJsonParserDLLPINVOKE.NLJsonASTList_RemoveRange(swigCPtr, index, count);
    if (NLJsonParserDLLPINVOKE.SWIGPendingException.Pending) throw NLJsonParserDLLPINVOKE.SWIGPendingException.Retrieve();
  }

  public static NLJsonASTList Repeat(NLJsonAST value, int count) {
    global::System.IntPtr cPtr = NLJsonParserDLLPINVOKE.NLJsonASTList_Repeat(NLJsonAST.getCPtr(value), count);
    NLJsonASTList ret = (cPtr == global::System.IntPtr.Zero) ? null : new NLJsonASTList(cPtr, true);
    if (NLJsonParserDLLPINVOKE.SWIGPendingException.Pending) throw NLJsonParserDLLPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    NLJsonParserDLLPINVOKE.NLJsonASTList_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    NLJsonParserDLLPINVOKE.NLJsonASTList_Reverse__SWIG_1(swigCPtr, index, count);
    if (NLJsonParserDLLPINVOKE.SWIGPendingException.Pending) throw NLJsonParserDLLPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, NLJsonASTList values) {
    NLJsonParserDLLPINVOKE.NLJsonASTList_SetRange(swigCPtr, index, NLJsonASTList.getCPtr(values));
    if (NLJsonParserDLLPINVOKE.SWIGPendingException.Pending) throw NLJsonParserDLLPINVOKE.SWIGPendingException.Retrieve();
  }

}
