//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum NLJsonType {
  nl_boolean,
  nl_null,
  nl_number,
  nl_string,
  nl_object,
  nl_array
}
