//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PegParserDLL {
  public static PegParser CreateParser(string grammar) {
    global::System.IntPtr cPtr = PegParserDLLPINVOKE.CreateParser(grammar);
    PegParser ret = (cPtr == global::System.IntPtr.Zero) ? null : new PegParser(cPtr, true);
    if (PegParserDLLPINVOKE.SWIGPendingException.Pending) throw PegParserDLLPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
